services:
  - docker:dind
stages:
  - build-image
  - build
  - test
build_image:
  stage: build-image
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
    - docker build -t ${REGISTRY}/selenium-hub-runner-image .
    - docker push ${REGISTRY}/selenium-hub-runner-image:latest
selenium-build:
  image: ${REGISTRY}/selenium-hub-runner-image
  stage: build
  script: docker-compose up -d && mvn test


maven-build:
  stage: test
  image: maven:3-jdk-8
  script: mvn test