services:
  - docker:dind

stages:
  - login
  - build
  - test
variables:
  DOCKER_DRIVER: overlay2

login:
  stage: login
  script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY}


run-selenium-tests:
  stage: test
  image: selenium-hub-runner-image
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY}
  script:
    - docker-compose up
