image: docker:latest
services:
  - selenium/standalone-chrome:latest

stages:
  - build
  - test

before_script:
  - apt-get update
  - export DISPLAY=:1
  - sleep 3

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: mvn test
