services:
  - docker:dind

stages:
  - build
  - test
variables:
  DOCKER_DRIVER: overlay2


run-selenium-tests:
  stage: test
  image: docker:stable
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY}
  script:
    - docker-compose up
    - docker run --name=selenium_test_runner ${REGISTRY}/selenium-hub-runner-image mvn test
