image: docker:latest

services:
  - docker:dind
  - selenium/standalone-chrome:latest
  - selenium/standalone-firefox:latest

stages:
  - clean
  - test

before_script:
  - apt-get update
  - export DISPLAY=:1
  - sleep 3

maven-clean:
  image: maven:latest
  stage: clean
  script: mvn clean

maven-test:
  image: maven:latest
  stage: test
  script: mvn test
