image: docker:latest
services:
  - docker:dind
  - selenium/standalone-chrome:latest
  - selenium/standalone-firefox:latest

stages:
  - build
  - test

before_script:
  - apt-get update
  - export DISPLAY=:1
  - sleep 3

maven-build:
  image: maven:latest
  stage: build
  script: mvn build

maven-test:
  image: maven:latest
  stage: test
  script: mvn test
