image: docker:latest

services:
  - selenium/standalone-chrome:latest
  - selenium/standalone-firefox:latest

stages:
  - clean
  - test

before_script:
  - docker info

maven-clean:
  image: maven:latest
  stage: clean
  script: mvn clean

maven-test:
  image: maven:latest
  stage: test
  script: mvn test
