image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

before_script:
  - apt-get update
  - export DISPLAY=:1
  - sleep 3

maven-build:
  image: maven:latest
  stage: build
  script: mvn test
