image: maven:latest

e2e:firefox:
  stage: confidence-check
  services:
    - selenium/standalone-firefox
  script:
    - mvn test

e2e:chrome:
  stage: confidence-check
  services:
    - selenium/standalone-chrome
  script:
    - mvn test
