services:
  - docker:dind

stages:
  - build-image
  - build
  - test
variables:
  DOCKER_DRIVER: overlay2

run-selenium-tests:
  stage: test
  image: docker:stable
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY}
  script:
    - docker run --network="host" ${REGISTRY}/selenium-hub-runner-image mvn test
