variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind
stages:
  - build
  - test

selenium-build:
  image: tmaier/docker-compose:latest
  stage: build
  script: docker-compose up -d \
          && mkdir -p /usr/share/maven /usr/share/maven/ref \
          && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
          && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha512sum -c - \
          && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
          && rm -f /tmp/apache-maven.tar.gz \
          && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn \
          && mvn test


maven-build:
  stage: test
  image: maven:3-jdk-8
  script: mvn test