services:
  - docker:dind

stages:
  - build
  - test
variables:
  DOCKER_DRIVER: overlay2


run-selenium-tests:
  stage: test
  image: selenium-hub-runner-image
  name: selenium_test_runner
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY}
  script:
    - docker-compose up
