variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind
stages:
  - build
  - test

selenium-build:
  image: tmaier/docker-compose:latest
  stage: build
  script: docker-compose up

maven-build:
  stage: test
  image: maven:3-jdk-8
  script: mvn test