variables:
  DOCKER_DRIVER: overlay2
  MAVEN_VERSION: 3.6.3
  BASE_URL: https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries
  SHA: c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0

services:
  - docker:dind
stages:
  - build
  - test
build_image:
  script:
    - docker build -t selenium-hub-runner-image .
selenium-build:
  image: selenium-hub-runner-image
  stage: build
  script: mvn test


maven-build:
  stage: test
  image: maven:3-jdk-8
  script: mvn test