services:
  - docker:dind
stages:
  - build
  - test
build_image:
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
    - docker build -t selenium-hub-runner-image .
selenium-build:
  image: selenium-hub-runner-image
  stage: build
  script: mvn test


maven-build:
  stage: test
  image: maven:3-jdk-8
  script: mvn test