services:
  - docker:dind

stages:
  - build-image
  - build
  - test
variables:
  DOCKER_DRIVER: overlay2

run-selenium-tests:
  stage: test
  image: ${REGISTRY}/selenium-hub-runner-image
  script: mvn test
