image: docker:latest
services:
  - docker:dind
  - selenium/standalone-chrome:latest
  - selenium/standalone-firefox:latest

stages:
  - build

before_script:
  - apt-get update
  - export DISPLAY=:1
  - sleep 3

maven-build:
  image: maven:latest
  stage: build
  script: mvn clean install
