services:
  - docker:dind

stages:
  - build-image
  - build
  - test
variables:
  DOCKER_DRIVER: overlay2


run-selenium-tests:
  stage: test
  image: docker:stable
  before_script:
    - docker network rm mul-fe-testing-network || true;
    - docker network create mul-fe-testing-network
  script:
    - docker run --network mul-fe-testing-network ${REGISTRY}/selenium-hub-runner-image mvn test
  after_script:
    - docker network rm mul-fe-testing-network
