services:
  - docker:dind
stages:
  - build-image
  - build
  - test
variables:
  DOCKER_DRIVER: overlay2


run-selenium-tests:
  image: ${REGISTRY}/selenium-hub-runner-image
  stage: test
  script: mvn test
