services:
  - docker:dind
stages:
  - build-image
  - build
  - test
variables:
  DOCKER_DRIVER: overlay2

build_image:
  stage: build-image
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
    - docker pull ${REGISTRY}/selenium-hub-runner-image:latest
    - docker build -t ${REGISTRY}/selenium-hub-runner-image .
    - docker push ${REGISTRY}/selenium-hub-runner-image:latest
run-selenium-tests:
  image: ${REGISTRY}/selenium-hub-runner-image
  stage: test
  script: mvn test
