image: maven:latest

services:
  - selenium/standalone-chrome:latest
  - selenium/standalone-firefox:latest

stages:
  - clean
  - test

clean:
  stage: clean
  script: mvn clean

test:
  stage: test
  script: mvn test
