build_image:
  stage: build-image
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
    - docker pull ${REGISTRY}/selenium-hub-runner-image:latest
    - docker build -t ${REGISTRY}/selenium-hub-runner-image .
    - docker push ${REGISTRY}/selenium-hub-runner-image:latest